foreground #{{TEXT}}
background #{{BG}}
background_opacity {{OPACITY}}
selection_foreground #{{CONTRAST}}
selection_background #{{ACCENT2}}
cursor #{{ACCENT2}}
cursor_text_color #{{CONTRAST}}
url_color #{{ACCENT}}
active_tab_foreground #{{CONTRAST}}
active_tab_background #{{ACCENT}}
inactive_tab_foreground #{{MUTED}}
inactive_tab_background #{{PANEL}}
color0 #{{C0}}
color1 #{{C1}}
color2 #{{C2}}
color3 #{{C3}}
color4 #{{C4}}
color5 #{{C5}}
color6 #{{C6}}
color7 #{{C7}}
color8 #{{C8}}
color9 #{{C9}}
color10 #{{C10}}
color11 #{{C11}}
color12 #{{C12}}
color13 #{{C13}}
color14 #{{C14}}
color15 #{{C15}}
