@define-color bg-solid #{{BG}};
@define-color panel-solid #{{PANEL}};
@define-color hover-solid #{{HOVER}};
@define-color border-solid #{{BORDER}};
@define-color bg @bg-solid;
@define-color panel @panel-solid;
@define-color hover @hover-solid;
@define-color border alpha(@border-solid, 0.44);
@define-color text #{{TEXT}};
@define-color muted #{{MUTED}};
@define-color accent #{{ACCENT}};
@define-color accent2 #{{ACCENT2}};
@define-color danger #{{DANGER}};
@define-color contrast #{{CONTRAST}};
