foreground #eee5d8
background #0d0c0c
background_opacity 0.92
selection_foreground #17130f
selection_background #e7c18c
cursor #e7c18c
cursor_text_color #17130f
url_color #d6a15f
active_tab_foreground #17130f
active_tab_background #d6a15f
inactive_tab_foreground #a49688
inactive_tab_background #181513
color0 #272321
color1 #dc806f
color2 #a7b58b
color3 #d6a15f
color4 #829eae
color5 #b38f9f
color6 #83aaa0
color7 #d8cec1
color8 #62584f
color9 #e99785
color10 #bfca9f
color11 #e7c18c
color12 #9eb9c7
color13 #c9a8b6
color14 #9bc1b6
color15 #f4ecdf
