color_theme = "obsidian-current"
theme_background = True
truecolor = True
rounded_corners = True
graph_symbol = "braille"
update_ms = 1500
proc_gradient = True
proc_colors = True
proc_tree = False
show_battery = True
